dist: trusty
language: android
android:
  components:
  - build-tools-29.0.2
  - android-29
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
  - extra-google-google_play_services
  licenses:
  - android-sdk-license-.+
before_install:
- yes | sdkmanager "platforms;android-29" # workaround for accepting the license
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $secrets_key -iv $secrets_iv -in "$PWD/.travis/secrets.tar.enc" -out secrets.tar -d;
    tar xf secrets.tar;
    mv keystore.jks "$HOME/.android";
  fi
- git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
- export ANDROID_NDK_HOME=$HOME/android-ndk-root
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
script: ".travis/build.sh"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
deploy:
  provider: releases
  api_key: "$GITHUB_KEY"
  file: "app-aligned.apk"
  draft: true
  skip_cleanup: true
  on:
    tags: true
