dist: trusty
language: android
android:
  components:
  - build-tools-29.0.2
  - android-29
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
  - extra-google-google_play_services
  licenses:
  - android-sdk-license-.+
before_install:
- yes | sdkmanager "platforms;android-29" # workaround for accepting the license
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $secrets_key -iv $secrets_iv -in "$PWD/.travis/secrets.tar.enc" -out secrets.tar -d;
    tar xf secrets.tar;
    mv keystore.jks "$HOME/.android";
  fi
- git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
- export ANDROID_NDK_HOME=$HOME/android-ndk-root
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
jobs:
  include:
    - stage: "Verification"
      name: "Checkstyle" 
      script: ./gradlew checkstyle
    - name: "Lint" 
      script: ./gradlew lint
    - stage: "Build"
      script: .travis/build.sh
      deploy:
        provider: releases
        api_key:
          secure: ZipG4psaqbjATw+JEAzzqVbimir/xmX/OZuazTHSEB/WTvIkYK5sKsPpSBvYT3Kn72P0H413LdgCzUe0Xywc35Yx69Nn/nasgWTZnZnV5fmLmKbflQ3PsCcY7RSH9FOMLyz+armeNTQOyQqxe2z5JEZrA1vPnJPzOm5b3hgrfr7B3M7obW3cpQxOtoHvBkQ4uct4vkUg/LAppjAfchvG/eZ5hUIvlKg0AoUxyd0s5IafEnOijVg680OxvETTzG8UOCHUChj67B0tQHcuk+GUlq24RngNgn8/Up3sNWFiAizNpxAQE8IPpkLf6+H7+Bu5BYyjG5snd4q8DAQSzOrDmUZQU2qY5V5Z+UuoeH/gIYondr90EBeRAJOuuIhE2f7JHBKR9O97dRrcUO/degSMygwrdZ2wFgaLNno61aRTnuwq63tOa2X+lbiHfVJv2DB6+sn3HUAgbZmk9edDbWMM199kr6Hjrz5DCT6M++CKbcoRNflt0md5ZuDQeNrod3zAieBM647IKPC/eoHYf8Jwwp1zp7VIy4gZddqqnD4Kj7JfH1+dez+/3wdPpsJ4p+cUx5g7+M4Kv+zUFiJRcGZIyTVVP/Qwmo0ZIW7dKbu3UB+p/48GT5p/i/Q+nRKSKp/+5kH3Mege/t2R+e85S2f30xTou5g/JoAzcDftKA8yBLI=
        file: app-aligned.apk
        skip_cleanup: true
        draft: true
        on:
          repo: shlchoi/tachiyomi
          tags: true
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"

